const data = {
  products: [
    {
      _id: "1",
      title: "Nike Slim Shirt",
      category: "robot",
      image: "/assets/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      title: "Adidas Fit Shirt",
      category: "robot",
      image: "/assets/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      title: "Lacoste Free Shirt",
      category: "robot",
      image: "/assets/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      title: "Nike Slim Pant",
      category: "robot",
      image: "/assets/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      title: "Puma Slim Pant",
      category: "robot",
      image: "/assets/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      title: "Adidas Fit Pant",
      category: "robot",
      image: "/assets/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "7",
      title: "Adidas Fit Pant",
      category: "robot",
      image: "/assets/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "8",
      title: "Adidas Fit Pant",
      category: "robot",
      image: "/assets/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
